name: Semantic Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.19
        uses: actions/setup-node@v1
        with:
          node-version: '12.19'
      - name: Clean install
        run: npm ci
      - name: Test
        run: npm test

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.19
        uses: actions/setup-node@v1
        with:
          node-version: '12.19'
      - run: npm install
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}